### PR TITLE
Apply clang fix (use cpphs) to freebsd as well

### PR DESCRIPTION
**Pull request by mitchellwrosen**

### CODE REVIEW

**Comment by erikd** [comment]
👍

**Comment by mitchellwrosen** [comment]
The Travis errors look unrelated

**Comment by mitchellwrosen** [comment]
Hello again! @erikd are you maintaining this repo? Or, do you know who is?

**Comment by erikd** [comment]
@mitchellwrosen I'm only a collaborator here and not even a very active one. I don't have sufficient permissions to merge this.

**Comment by liyang** [comment]
Sorry about this. It looks fine to me.

**Pull request merged**
